# 주식 데이터 수집 - yfinance

야후 파이낸스에서 크롤링한 데이터를 제공하는 라이브러리

재무제표, 주주정보 등 수집하기 어려운 다양한 데이터도 제공

야후 파이낸스 특성상 미국 주식 데이터는 정확하지만 국내 주식 데이터는 불안정

## #01. 준비과정

### [1] 패키지 참조

In [1]:
import yfinance as yf

## #02. 주가 검색

검색을 원하는 종목의 종목번호를 알아야 한다. (야후 파이낸스)

![그림](종목번호_예시.png)

> 종목번호 : 005930.KS

### 반환되는 컬럼의 의미
| Open | High | Low | Close | Adj Close | Volume |
|---|---|---|---|---|---|
| 시작가 | 고가 | 저가 | 종가 | 조정 종가 | 거래량 |

조정 종가 :

In [5]:
# 종목번호, 검색시작일, 검색종료일 지정
# 종목번호 : (삼성 : 005930.KS), (애플 : AAPL)
# 검색 종료일을 지정하지 않을 경우 가장 최근까지 검색한다.
df = yf.download("005930.KS", '2023-01-01', "2023-12-14")
df
# 검색결과를 판다스의 데이터프레임형태로 반환해준다

[*********************100%%**********************]  1 of 1 completed

1 Failed download:
['SAMSUNG_ELECTRONICS_CO._LTD.']: Exception('%ticker%: No timezone found, symbol may be delisted')

Empty DataFrame
Columns: [Open, High, Low, Close, Adj Close, Volume]
Index: []

## #03. 그 밖의 정보

### 특정 종목을 의미하는 객체 생성

In [8]:
aapl_yf = yf.Ticker("AAPL")
aapl_yf

yfinance.Ticker object <AAPL>

### 재무재표

In [10]:
aapl_yf.financials

,2023-09-30,2022-09-30,2021-09-30,2020-09-30
Tax Effect Of Unusual Items,0.0,0.0,0.0,0.0
Tax Rate For Calcs,0.147192,0.162045,0.133023,0.144282
Normalized EBITDA,125820000000.0,130541000000.0,120233000000.0,77344000000.0
Net Income From Continuing Operation Net Minority Interest,96995000000.0,99803000000.0,94680000000.0,57411000000.0
Reconciled Depreciation,11519000000.0,11104000000.0,11284000000.0,11056000000.0
Reconciled Cost Of Revenue,214137000000.0,223546000000.0,212981000000.0,169559000000.0
EBITDA,125820000000.0,130541000000.0,120233000000.0,77344000000.0
EBIT,114301000000.0,119437000000.0,108949000000.0,66288000000.0
Net Interest Income,NaN,-106000000.0,198000000.0,890000000.0
Interest Expense,NaN,2931000000.0,2645000000.0,2873000000.0
Interest Income,NaN,2825000000.0,2843000000.0,3763000000.0
Normalized Income,96995000000.0,99803000000.0,94680000000.0,57411000000.0
Net Income From Continuing And Discontinued Operation,96995000000.0,99803000000.0,94680000000.0,57411000000.0
Total Expenses,268984000000.0,274891000000.0,256868000000.0,208227000000.0
Total Operating Income As Reported,114301000000.0,119437000000.0,108949000000.0,66288000000.0
Diluted Average Shares,15812547000.0,16325819000.0,16864919000.0,17528214000.0
Basic Average Shares,15744231000.0,16215963000.0,16701272000.0,17352119000.0
Diluted EPS,6.13,6.11,5.61,3.28
Basic EPS,6.16,6.15,5.67,3.31
Diluted NI Availto Com Stockholders,96995000000.0,99803000000.0,94680000000.0,57411000000.0
Net Income Common Stockholders,96995000000.0,99803000000.0,94680000000.0,57411000000.0
Net Income,96995000000.0,99803000000.0,94680000000.0,57411000000.0
Net Income Including Noncontrolling Interests,96995000000.0,99803000000.0,94680000000.0,57411000000.0
Net Income Continuous Operations,96995000000.0,99803000000.0,94680000000.0,57411000000.0
Tax Provision,16741000000.0,19300000000.0,14527000000.0,9680000000.0
Pretax Income,113736000000.0,119103000000.0,109207000000.0,67091000000.0
Other Income Expense,-565000000.0,-334000000.0,258000000.0,803000000.0
Other Non Operating Income Expenses,-565000000.0,-334000000.0,258000000.0,803000000.0
Net Non Operating Interest Income Expense,NaN,-106000000.0,198000000.0,890000000.0
Interest Expense Non Operating,NaN,2931000000.0,2645000000.0,2873000000.0
Interest Income Non Operating,NaN,2825000000.0,2843000000.0,3763000000.0
Operating Income,114301000000.0,119437000000.0,108949000000.0,66288000000.0
Operating Expense,54847000000.0,51345000000.0,43887000000.0,38668000000.0
Research And Development,29915000000.0,26251000000.0,21914000000.0,18752000000.0
Selling General And Administration,24932000000.0,25094000000.0,21973000000.0,19916000000.0
Gross Profit,169148000000.0,170782000000.0,152836000000.0,104956000000.0
Cost Of Revenue,214137000000.0,223546000000.0,212981000000.0,169559000000.0
Total Revenue,383285000000.0,394328000000.0,365817000000.0,274515000000.0
Operating Revenue,383285000000.0,394328000000.0,365817000000.0,274515000000.0

### 주식 보유 지분

In [11]:
aapl_yf.major_holders

        0                                      1
0   0.07%        % of Shares Held by All Insider
1  61.66%       % of Shares Held by Institutions
2  61.71%        % of Float Held by Institutions
3    5888  Number of Institutions Holding Shares